AY1920S1-CS2103T-T09-4/main

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/CustomerBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/OrderBook.java, src/main/java/seedu/address/model/PhoneBook.java, src/main/java/seedu/address/model/ReadOnlyDataBook.java, src/main/java/seedu/address/model/ScheduleBook.java, src/main/java/seedu/address/model/order/UniqueOrderList.java, src/main/java/seedu/address/model/order/exceptions/DuplicateOrderException.java, src/main/java/seedu/address/model/order/exceptions/OrderNotFoundException.java, src/main/java/seedu/address/model/phone/UniquePhoneList.java, src/main/java/seedu/address/model/phone/exceptions/DuplicatePhoneException.java, src/main/java/seedu/address/model/phone/exceptions/PhoneNotFoundException.java, src/main/java/seedu/address/model/schedule/UniqueScheduleList.java, src/main/java/seedu/address/model/schedule/exceptions/DuplicateScheduleException.java, src/main/java/seedu/address/model/schedule/exceptions/ScheduleNotFoundException.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Add CustomerBook, OrderBook, PhoneBook and ScheduleBook
Update Model and ModelManager
Add UniqueOrderList, UniquePhoneList and UniqueScheduleList
=> Update Model Manager

src/main/java/seedu/address/logic/commands/AddCustomerCommand.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java, src/main/java/seedu/address/logic/commands/EditCustomerCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/FindCustomerCommand.java, src/main/java/seedu/address/logic/commands/FindOrderCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/ListCustomerCommand.java, src/main/java/seedu/address/logic/commands/ListOrderCommand.java, src/main/java/seedu/address/logic/commands/ListPhoneCommand.java, src/main/java/seedu/address/logic/commands/ListScheduleCommand.java, src/main/java/seedu/address/logic/commands/PanelType.java, src/main/java/seedu/address/logic/commands/UiChange.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/exception/EnumNotPresentException.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/ExitCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Fixed the CommandResult to not have to deal with the boolean fields
=> Help exit command

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/ReadOnlyUserPrefs.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/JsonAdaptedPhone.java, src/main/java/seedu/address/storage/JsonCustomerBookStorage.java, src/main/java/seedu/address/storage/JsonPhoneBookStorage.java, src/main/java/seedu/address/storage/JsonSerializablePhoneBook.java, src/main/java/seedu/address/storage/PhoneBookStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java
Added Phone storage. Similar to Customer storage.
=> Added phone storage

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/CancelOrderCommand.java, src/main/java/seedu/address/logic/commands/addcommand/AddOrderCommand.java, src/main/java/seedu/address/logic/commands/editcommand/EditOrderCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CancelOrderCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/addcommandparser/AddOrderCommandParser.java, src/main/java/seedu/address/logic/parser/editcommandparser/EditOrderCommandParser.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/ui/cards/OrderCard.java, src/main/resources/view/OrderListCard.fxml
Commands and parsers for Orders.
=> Add commands and parsers for Orders and add sample data for OrderBook

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/ReadOnlyUserPrefs.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/JsonAdaptedSchedule.java, src/main/java/seedu/address/storage/JsonScheduleBookStorage.java, src/main/java/seedu/address/storage/JsonSerializableScheduleBook.java, src/main/java/seedu/address/storage/ScheduleBookStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java
Added storage files for Schedule. Just like customers and phones.
=> Added Schedule storage.

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/ReadOnlyUserPrefs.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/storage/JsonAdaptedOrder.java, src/main/java/seedu/address/storage/JsonOrderBookStorage.java, src/main/java/seedu/address/storage/JsonSerializableOrderBook.java, src/main/java/seedu/address/storage/OrderBookStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java
Add Order Storage. Not yet edited mainapp to load from saved data.
=> Add Order storage

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/LogicManager.java
Modify initModelManager method to test Storage
=> Integration Testing

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/addcommand/AddPhoneCommand.java, src/main/java/seedu/address/logic/commands/statisticcommand/StatsCommand.java
=> minor string adjustments

src/main/java/seedu/address/logic/commands/CancelOrderCommand.java
Deletes a schedule tagged to the order that is cancelled if any.
=> Fix CancelOrderCommand bug

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/schedule/Schedule.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedOrder.java, src/main/java/seedu/address/storage/JsonAdaptedPhone.java, src/main/java/seedu/address/storage/JsonAdaptedSchedule.java, src/main/java/seedu/address/storage/JsonOrderBookStorage.java, src/main/java/seedu/address/storage/JsonScheduleBookStorage.java, src/main/java/seedu/address/storage/JsonSerializableOrderBook.java, src/main/java/seedu/address/storage/JsonSerializableScheduleBook.java
Fixed loadable for Phone and Order at the moment. 
Currently working: Customer, Phone, Order.
=> Fix json adapted files

docs/diagrams/StorageClassDiagram.puml
Edit UG/DG + Add StorageClassDiagram
=> Added StorageClassDiagram

src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
Fixed bug when saving the schedule.
=> Fix JsonAdaptedSchedule month issue.

build.gradle, src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/commands/ExportCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ExportCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java
Added Export command, 
export [filename] creates a filename.csv containing the data ready to be imported into excel.
=> Added Export to CSV feature

docs/UserGuide.adoc
Updated UG for export command, removed import command
=> Updated UG for export command

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/testutil/ModelStub.java
Fix OrderBook Conflict Resolution Bug 
Added Orders into ArchivedOrderBook
=> Fix OrderBook Conflict Resolution Bug

src/main/java/seedu/address/MainApp.java
OrderBook cannot be read after saving bug
=> Fix OrderBook cannot be read after saving bug

docs/UserGuide.adoc, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/addcommand/AddScheduleCommand.java, src/main/java/seedu/address/logic/commands/clearcommand/ClearScheduleCommand.java, src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java, src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/panels/CalendarPanel.java, src/test/java/seedu/address/logic/commands/addcommand/AddScheduleCommandTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Reverts AY1920S1-CS2103T-T09-4/main#222
=> Revert "Fix bugs + make schedule commands undoable"

docs/DeveloperGuide.adoc
=> Updated DG for export feature

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java, src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java, src/main/java/seedu/address/model/ModelManager.java
=> Fix pe bugs 

src/main/java/seedu/address/logic/commands/ExportCommand.java
Added limit to file name, and made file name alphanumeric only
=> Filename bug fix

src/main/java/seedu/address/MainApp.java
Data file is created before any command to allow export.
=> Fix issue: Create data folder during init

docs/UserGuide.adoc
=> fixed typo for UG
